### ISSUE TITLE
建议增加996授权协议

### ISSUE THREAD

**Issue by ravepm** [lxlxw/996.TSC#12]
建议增加996授权协议

**Comment by lxlxw** [comment]
可以pr把996协议引进来

**Comment by fightforlifev** [comment]
![image](https://user-images.githubusercontent.com/49082193/55268135-3c084080-52db-11e9-89ce-b16c18881204.png)

**Comment by funnypro** [comment]
现在我对那个授权有一些疑问

例如：那个协议能作为其他协议的附加协议什么的吗？

**Comment by shuiRong** [comment]
协议已经添加进来了，
另外，静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）。
