### ISSUE TITLE
感觉这个项目没有人关注，其实，图片比文字更具有影响力。

### ISSUE THREAD

**Issue by fastharry** [lxlxw/996.TSC#15]
期望前端、设计同学的更好创意。

健康最重要！

希望这个相关项目只做公益，不要商业化！

**Comment by lxlxw** [comment]
嗯，是只做公益，不做商业，也不可能做商业。

**Comment by fastharry** [comment]
为了那些正在996的人，为了那些和996相关的家人，为了那些即将毕业的同学，为了更好更合理的工作大环境，这个项目很有意义，很值得！

For the 996 people, for the 996-related family members, for the graduating students, and for a better and more reasonable working environment, this project is meaningful and worthwhile!

**Comment by shuiRong** [comment]
静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
