### ISSUE TITLE
匿名投票网站中文搜索没用

### ISSUE THREAD

**Issue by chansonzhang** [lxlxw/996.TSC#16]
https://feathub.com/LinXueyuanStdio/996.ICU
这个网址，中文搜索不能用

**Comment by shuiRong** [comment]
这个你可以联系[所有者](https://github.com/LinXueyuanStdio/996.ICU)。
不过我看现在这个站点都被插入存储型xss了23333

另外，静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
