### ISSUE TITLE
icon 我醉了  

### ISSUE THREAD

**Issue by goodking-bq** [lxlxw/996.TSC#2]

**Comment by lxlxw** [comment]
提交更多更好的作品吧~

**Comment by szhielelp** [comment]
T shirt 的丑死了....o(*￣▽￣*)o

**Comment by lxlxw** [comment]
> T shirt 的丑死了....o(_￣▽￣_)o

欢迎提交更好的产品~社区应该会有厉害的设计师

**Comment by junxy** [comment]
那个 pornhub style logo 那天看到了一个在线生成器 <https://github.com/bestony/logoly> 😆

**Comment by shuiRong** [comment]
静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
