### ISSUE TITLE
I build a 996icu-tsc channel in the 996.ICU slack workspace. welcome you guys join this channel.

### ISSUE THREAD

**Issue by fengshenyuan** [lxlxw/996.TSC#22]
在996.ICU slack的workplace上建了一个996icu-tsc 交流用的channel, 欢迎tsc相关的童鞋加入.

**Comment by torchina** [comment]
**聊天室 - 没有自我审查**

**https://gitter.im/torchina/community**

**Tor 浏览器 8.0.8 - 绕过gfw**

![Tor Browser](https://github.com/torchina/get/blob/master/2019-04-06_22-27-39.png?raw=true)

**https://torchina.github.io/get**

**Comment by shuiRong** [comment]
静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
