### ISSUE TITLE
五月四号周六，能否组织一次游行

### ISSUE THREAD

**Issue by pipijoe** [lxlxw/996.TSC#29]

**Comment by firedom** [comment]
目前不建议搞。如果短时间内就把这个问题上升为政治问题，反而会给解决996问题带来负面影响。

**Comment by theprinceiherelf** [comment]
不行，不能聚众，否则行为性质不一样，反而不利于解决问题。

**Comment by devguo** [comment]
#44 发个微博朋友圈，qq签名就行了，效果不会比上街差。

**Comment by ShuaiShuaiLee** [comment]
> 
> 
> _No description provided._

你是想去派出所吗？
