### ISSUE TITLE
建议建立专门的网站，以便让设计师、法律相关人士使用

### ISSUE THREAD

**Issue by hyliang96** [lxlxw/996.TSC#32]
对于非技术岗，github使用起来有难度，注册账号、上传下载文件、添加issue等等都需要专人指导。为了方便各岗位的工作者参与996ICU的活动，建议建立专门网站，其中包括不限于法律、周边、投票、许可等板块。

**Comment by CaliInn-Li** [comment]
主要是996的意义一部分在开源的许可上，而这个限制最多的还是经常使用开源社区代码的科技公司

**Comment by shuiRong** [comment]
好想法，让非程序员的人也能很快熟悉Github的使用。也没必要非得一个网站为载体，一篇教程，然后知乎、微博等各个地方传播下也挺好

另外，静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
