### ISSUE TITLE
这么做会不会让人觉得996.icu只是一场营销? 是不是有所不妥? 

### ISSUE THREAD

**Issue by noyidoit** [lxlxw/996.TSC#34]
个人之见, 理性讨论.

**Comment by noyidoit** [comment]
壁纸, 头像之类的创意我觉得挺好的, 但是文化衫......希望不要做成一桩生意了, 虽然可能并不是什么大生意, 但有让996.icu这一活动失去其纯洁性的风险.

**Comment by lxlxw** [comment]
> 壁纸, 头像之类的创意我觉得挺好的, 但是文化衫......希望不要做成一桩生意了, 虽然可能并不是什么大生意, 但有让996.icu这一活动失去其纯洁性的风险.

已在readme中体现出了该rep的性质，如果还不够明显，欢迎pr

**Comment by lxlxw** [comment]
本意就只是996衍生性质的rep，想着用图片等形式传播这个活动，并不会商用。

**Comment by shuiRong** [comment]
996.ICU是营销？又不涉及金钱，营销什么呢...文化衫只是图片而已，我们也不会卖它。（本repo不会通过996来赚钱的！）

另外，静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）

先关闭这个issue了，如果还想继续讨论，喊我，我重开
