### ISSUE TITLE
T-shirt/T-2.jpg 没传完成？996icu3.jpg大图

### ISSUE THREAD

**Issue by gMan1990** [lxlxw/996.TSC#35]
感觉被裁剪错了~~~边缘字体显示不全

**Comment by gMan1990** [comment]
# 996icu3.jpg
![996icu3.jpg](http://s2.sinaimg.cn/large/003yzfMAgy6Mh5xd6Ex31&690)

**Comment by shuiRong** [comment]
静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）

**Comment by gMan1990** [comment]
已被河蟹~ https://www.biliplus.com/video/av49504696/
土鳖神秘代码: QvmC-WnKIAI
https://bilidata.1mc.site/index 未收录
