### ISSUE TITLE
建议996icu推广活动

### ISSUE THREAD

**Issue by devguo** [lxlxw/996.TSC#44]
每年某天，比如1024，可以号召大家社交头像改成996icu，发个朋友圈或者动态之类的，毕竟gayhub圈子都是自己人，影响范围不够大。
如果要蹭现在的热度，一起定个日子换个头像，发个朋友圈,微博之类的，这种不上街，随手的事情，更容易传达码农的态度。发不发都是自愿。看大神制作的图片很厉害了，如果可以加点创意，让大家更加愿意传播，那就完美了。

**Comment by shuiRong** [comment]
每年某天，比如1024，可以号召大家社交头像改成996icu，发个朋友圈或者动态之类的，毕竟gayhub圈子都是自己人，影响范围不够大。
如果要蹭现在的热度，一起定个日子换个头像，发个朋友圈,微博之类的，这种不上街，随手的事情，更容易传达码农的态度。发不发都是自愿。看大神制作的图片很厉害了，如果可以加点创意，让大家更加愿意传播，那就完美了。

**Comment by shuiRong** [comment]
可行，建议在相关群组里聊这个事儿，人少的地方搞不动...

另外，静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）

先关闭issue了，如果还想讨论，喊我，我重开
