### ISSUE TITLE
建议建一个996.TSC的网站！

### ISSUE THREAD

**Issue by ShuaiShuaiLee** [lxlxw/996.TSC#45]
建议建一个996.TSC的网站！

**Comment by wjw12** [comment]
现在这个repo看图片很不方便，影响力不够，希望有前端同学努把力！

**Comment by rpfbl** [comment]
有 .tsc 域名后缀吗？

**Comment by ersaijun** [comment]
有 .tsc 域名后缀吗？

**Comment by shuiRong** [comment]
没有.tsc后缀，然后996tsc.com/cn域名已经被人注册了，无语。
静态网站既然还没写出来，那我来搞（我前端开发者），这两天就能把基本版本写出来，可以正常使用。
麻烦 @lxlxw 联系我（可以的话，邮件我一个能联系到你的方式: shuirong1997@icloud.com ），这两天我网站（静态网站）写出来后，会提个PR，因此希望能及时联系到你。

**Comment by shuiRong** [comment]
静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）

**Comment by ersaijun** [comment]
@shuiRong 访问速度很慢，加载不出来
