### ISSUE TITLE
哈人，删了

### ISSUE THREAD

**Issue by Hickoo** [lxlxw/996.TSC#46]
哈人，删了

**Comment by firedom** [comment]
事实上只要你有足够的证据就可以起诉非法用工的企业，国家以及相关法律是站在劳动者这边的。只要你有勇气走出第一步并说出你所遇到的问题，就会有人向你提供意见以及给予一定的帮助。

成立工会并不是不可，但是工会很容易为了获得更多的利益而投靠无良的企业/资本家，反而会增加劳动者维权的成本和难度。

相关的法律工具和资源可以在这里查找：
https://github.com/Y1ran/996.Law

**Comment by wjw12** [comment]
这和民主没关系，建议不要谈论这些敏感词。我们国家有劳动法的，现在是有法不依、执法不严的问题，可以用合法方式维权

**Comment by ghost** [comment]
哈人，删了

**Comment by ghost** [comment]
哈人，删了

**Comment by charming7201** [comment]
一直都有相关的法律约束，只是没人去维权罢了。

**Comment by Z60** [comment]
我们的反996行动建立在中国有一个健全的民主法律制度的框架下，这个制度的运转可能还不尽如人意，但是我们的目标就是让这个制度更好的运转

**Comment by juruo221** [comment]
> 这和民主没关系，建议不要谈论这些敏感词。我们国家有劳动法的，现在是有法不依、执法不严的问题，可以用合法方式维权
民主一个很正常的词汇，如果这在某个国度都成为了敏感词的话，那生活在那个国度的人民是不是很可怜呢？

**Comment by juruo221** [comment]
> 这和民主没关系，建议不要谈论这些敏感词。我们国家有劳动法的，现在是有法不依、执法不严的问题，可以用合法方式维权

民主一个很正常的词汇，如果这在某个国度都成为了敏感词的话，那生活在那个国度的人民是不是很可怜呢？

**Comment by xlhandsome** [comment]
没卵用，民主了就是金融和寡头政治，有钱人是老大，那样资本家就名正言顺的登堂入室了

**Comment by choetClear** [comment]
民主不过我知道。这一定是个恶性循环，有能力的人远走，要发展只有对没有能力的加大压迫。相信有可能：
- 有公司的制度会写上一周基本工时160小时（没有干预下会发展的顶峰）。没有办法，越来越多会不相信他们了，除了没有办法走的人。矛盾会越来越激化。
- 还有个问题就是越来越多的人就走了，没有走到生育意愿多强呢？表示有说法是大多数名人都去国外了嘛。之后的情况，不用想都知道吧？
如果，长此以往就会造成。现在，你看看大学毕业出国的人回来有多少呢？诸多矛盾已经开始深化，企业只会更过分。

**Comment by Hickoo** [comment]
> 

 社会左转太哈人了，删了删了
