### ISSUE TITLE
微信交流群

### ISSUE THREAD

**Issue by Jadyli** [lxlxw/996.TSC#49]
旨在提供一个交流的环境，不要发广告哦。
![image](https://user-images.githubusercontent.com/15962904/55486640-3d30c900-565f-11e9-8eb8-243130f19a84.png)

**Comment by paretozone** [comment]
深圳的朋友，欢迎加入
<img width="663" alt="2" src="https://user-images.githubusercontent.com/13246785/55522213-8e1fdc00-56b6-11e9-82c0-5fda3da16bcc.png">

**Comment by timruning** [comment]
建立这么多群力量不集中

**Comment by shuiRong** [comment]
静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
