### ISSUE TITLE
建了一个相关微博账号，欢迎关注与转发

### ISSUE THREAD

**Issue by Yves-X** [lxlxw/996.TSC#51]
账号在此：**[@PETD亚洲善待开发者组织](https://weibo.com/6693620155)**

还没有想好该怎么用，对微博运营也没有经验。但隔空喊话总是被动，人们根本不上技术社区，有微博账号就能主动发表、评论和回击一些东西。
与 996.ICU 本身保持了一点距离，或许能有更好的效果。

目前是小透明状态，未来也会持续报道一些在专注于技术讨论的 V2EX 会进水深火热、但实际上并不至于那么敏感的话题的。欢迎关注与扩散 :)

**Comment by shuiRong** [comment]
静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
