### ISSUE TITLE
既然是周边，那是不是应该造个节日出来

### ISSUE THREAD

**Issue by fengzhouxuan** [lxlxw/996.TSC#6]

**Comment by funnypro** [comment]
请问：那应该定在哪一天？

**Comment by cc976655** [comment]
> 请问：那应该定在哪一天？

9月6号

**Comment by lxlxw** [comment]
> > 请问：那应该定在哪一天？
> 
> 9月6号

应该定在发起运动的那天才对，即996.icu这个项目在github创建的时间

**Comment by shuiRong** [comment]
节日的事情，建议在[主站](https://github.com/996icu/996.ICU/pulls)发起个PR，来讨论。那边人多，然后节日的事情也需要争取大多数的认可，就成了。
