### ISSUE TITLE
我们是否可以成立一个公益组织,来帮助被996剥削的朋友

### ISSUE THREAD

**Issue by 332065255** [lxlxw/996.TSC#67]
公益组织是合法合规的,在国内,完全可以通过吸纳会员,来起到另一种工会形式,来和资本家进行平等对话

**Comment by shuiRong** [comment]
关于”行动“，有专门的repo在做：[996.law](https://github.com/CPdogson/996.law) [996.action](https://github.com/CPdogson/996action)

另外，静态站点已经建成：https://996tsc.netlify.com （号召大家传播和贡献周边资源）
