### ISSUE TITLE
996成为文化，是不是也就是让程序员适应996？

### ISSUE THREAD

**Issue by stonesis** [lxlxw/996.TSC#71]
我对这个文化周边持有怀疑态度。是不是程序员只能自嘲？有什么意义吗？

**Comment by shuiRong** [comment]
回标题：绝不是！ 是为了给996.ICU造势，宣传，最终是为了传达 Anti-996 的想法。

程序员只能自嘲？当然不是！更多“行动”你可以在这里[找到](https://github.com/996icu/996.ICU/blob/master/README_CN.md#社区)
