### ISSUE TITLE
996不是“9点睡9点起，每天工作6小时”

### ISSUE THREAD

**Issue by stonesis** [lxlxw/996.TSC#72]
这个文化周边太坏了。

**Comment by shuiRong** [comment]
标题什么意思？ 文档某处有写错996的解释文本了吗？

另外，文化太坏了怎么理解？

**Comment by stonesis** [comment]
![T-10 847da6b](https://user-images.githubusercontent.com/16331837/56484302-595ab400-6501-11e9-9e4a-5be167a2c32f.jpg)
这个图片，从https://996tsc.netlify.com/#/tshirt找到的

**Comment by shuiRong** [comment]
我疏忽了，扫了一眼，没细看文本。我这就去掉，另外重新全部检查一遍图片。感谢提醒🙏
