### ISSUE TITLE
真会赚钱啊

### ISSUE THREAD

**Issue by LyShine** [lxlxw/996.TSC#75]
996的程序员还没申请到自己的权益呢, 就有人玩周边, 在那些人身上赚钱了. 我就想问这个周边有什么意思? 除了骗钱?

**Comment by shuiRong** [comment]
周边==赚钱？ 表情包、恶搞视频、段子、网友设计的T-Shirt（仅图片，不打算印制）。你说哪个和钱有关系？

你既然说赚钱，请拿出任何本repo所有者正在用此项目赚钱的**“证据”**
